name: GitHub Metrics

on:
  # Schedule updates (every 24 hours)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: kiritocroft
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          
          # Display stats on your GitHub account
          plugin_lines: yes
          plugin_traffic: yes
          
          # Display most used languages
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          
          # Display your latest achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed
          
          # Display your latest activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          
          # Display your latest posts from a source
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugin_posts_limit: 4
          
          # Display your stargazers and watchers
          plugin_stargazers: yes
          
          # Display your latest tweets
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_user: your_twitter_username
          plugin_tweets_limit: 2