name: GitHub Streak Stats

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

jobs:
  update-streak:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: DenverCoder1/github-readme-streak-stats@main
        with:
          user: kiritocroft
          theme: tokyonight
          hide_border: true
          OUTPUT: generated/streak.svg